version: '3'
services:
  jobhub_db:
    image: mysql
    container_name: jobhub_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_PASSWORD=Letmein123
      - MYSQL_DATABASE=jobhub
      - MYSQL_USER=huytran
    volumes:
      - jobhub_mysql:/var/lib/mysql 
    networks:
      - jobhub_net
  elasticsearch: 
    container_name: jobhub_es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - node.name=es01
      - ELASTIC_PASSWORD=Letmein123
      - ELASTIC_USERNAME=root
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - jobhub_net
  kibana: 
    depends_on:
      - elasticsearch
    container_name: jobhub_kibana
    image: docker.elastic.co/kibana/kibana:8.4.0
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_PASSWORD=Letmein123
      - ELASTIC_USERNAME=root
    networks:
      - jobhub_net
volumes:
  jobhub_mysql: 
  es-data:
    driver: local
  kibana-data:
    driver: local
networks:
  jobhub_net: